# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZHUVTKDT5ULpJSZz1yzGg6ErMZ3XvQVq
"""

# app.py
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import tensorflow as tf

# -----------------------
# Load model and files
# -----------------------
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model("ann_model.keras")  # ANN model
    return model

@st.cache_resource
def load_encoder():
    # Agar encoding use ki thi, otherwise skip
    try:
        encoder = joblib.load("encoder.pkl")
        return encoder
    except:
        return None

@st.cache_data
def load_data():
    df = pd.read_csv("customer_data.csv")
    return df

# Load everything
model = load_model()
encoder = load_encoder()
df = load_data()

# -----------------------
# Sidebar - Navigation
# -----------------------
st.sidebar.title("Churn Dashboard")
menu = ["Home", "EDA", "Prediction"]
choice = st.sidebar.selectbox("Menu", menu)

# -----------------------
# Home
# -----------------------
if choice == "Home":
    st.title("Customer Churn Dashboard")
    st.write("""
        This dashboard allows you to:
        - Explore customer data
        - Predict churn probability using ANN model
    """)
    st.write(f"Dataset Shape: {df.shape}")
    st.dataframe(df.head())

# -----------------------
# EDA / Data Analysis
# -----------------------
elif choice == "EDA":
    st.header("Exploratory Data Analysis")

    st.subheader("Dataset Overview")
    st.write(df.describe())

    st.subheader("Categorical Columns")
    cat_cols = df.select_dtypes(include='object').columns
    st.write(df[cat_cols].nunique())

    st.subheader("Churn Distribution")
    st.bar_chart(df['churn'].value_counts())

# -----------------------
# Prediction
# -----------------------
elif choice == "Prediction":
    st.header("Predict Customer Churn")

    st.write("Enter customer details:")

    # Example inputs - adjust according to your features
    age = st.number_input("Age", min_value=18, max_value=100, value=30)
    account_tenure = st.number_input("Account Tenure (Months)", min_value=0, max_value=600, value=12)
    credit_cards_count = st.number_input("Credit Cards Count", min_value=0, max_value=10, value=1)
    installment_loans_count = st.number_input("Installment Loans Count", min_value=0, max_value=10, value=0)
    ccfp_products_count = st.number_input("CCFP Products Count", min_value=0, max_value=10, value=0)
    atm_trans_3m = st.number_input("ATM Transactions (3M)", min_value=0, max_value=1000, value=10)
    total_trans_3m = st.number_input("Total Transactions (3M)", min_value=0, max_value=5000, value=50)

    # Add more fields as per your dataset

    input_dict = {
        "age": age,
        "account_tenure_months": account_tenure,
        "credit_cards_count": credit_cards_count,
        "installment_loans_count": installment_loans_count,
        "ccfp_products_count": ccfp_products_count,
        "atm_trans_count_3m": atm_trans_3m,
        "total_trans_count_3m": total_trans_3m
    }

    input_df = pd.DataFrame([input_dict])

    # If encoder exists, apply transformation
    if encoder:
        input_df = encoder.transform(input_df)

    # Prediction
    if st.button("Predict Churn"):
        pred_prob = model.predict(input_df)[0][0]
        st.write(f"Churn Probability: {pred_prob:.2f}")
        if pred_prob > 0.5:
            st.warning("⚠️ High risk of churn!")
        else:
            st.success("✅ Low risk of churn")