# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZHUVTKDT5ULpJSZz1yzGg6ErMZ3XvQVq
"""

# app.py
import streamlit as st
import pandas as pd
import joblib
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from zipfile import ZipFile
import os

st.set_page_config(page_title="Customer Churn Dashboard", layout="wide")

# =======================
# 1️⃣ Load ZIP & CSV
# =======================
zip_path = "customer_data.zip"

if not os.path.exists("customer_data.csv"):
    with ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall()

@st.cache_data
def load_data():
    df = pd.read_csv("customer_data.csv")
    return df

df = load_data()

# =======================
# 2️⃣ Load ANN Model & Features
# =======================
model = tf.keras.models.load_model("ann_model.keras")
feature_columns = joblib.load("feature_columns.pkl")

# =======================
# 3️⃣ Sidebar for pages
# =======================
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["EDA & Graphs", "Churn Prediction"])

# =======================
# 4️⃣ EDA & Graphs Page
# =======================
if page == "EDA & Graphs":
    st.title("Customer Churn Dashboard - EDA")

    st.subheader("Dataset Overview")
    st.dataframe(df.head(10))

    st.subheader("Summary Statistics")
    st.write(df.describe())

    st.subheader("Visualizations")

    # Example Graph 1: Age vs Churn
    fig, ax = plt.subplots()
    sns.boxplot(x='churn', y='age', data=df, ax=ax)
    ax.set_title("Age vs Churn")
    st.pyplot(fig)

    # Example Graph 2: Account Tenure vs Churn
    fig2, ax2 = plt.subplots()
    sns.histplot(data=df, x='account_tenure_months', hue='churn', bins=30, kde=True, ax=ax2)
    ax2.set_title("Account Tenure vs Churn")
    st.pyplot(fig2)

# =======================
# 5️⃣ Prediction Page
# =======================
elif page == "Churn Prediction":
    st.title("Customer Churn Prediction")
    st.write("Enter customer features to predict churn probability.")

    # Dynamic input for numeric features
    customer_input = {}
    numeric_features = ['age', 'account_tenure_months', 'credit_cards_count',
                        'installment_loans_count', 'ccfp_products_count',
                        'atm_trans_count_3m', 'atm_trans_amount_3m', 'total_trans_count_3m']

    st.subheader("Numeric Features")
    for feat in numeric_features:
        min_val = int(df[feat].min())
        max_val = int(df[feat].max())
        default_val = int(df[feat].mean())
        customer_input[feat] = st.number_input(feat, min_value=min_val, max_value=max_val, value=default_val)

    # Example for categorical features
    package_options = [col for col in df.columns if col.startswith("package_type")]
    st.subheader("Package Type")
    selected_package = st.selectbox("Select Package", package_options)

    # Create dataframe for model
    input_df = pd.DataFrame([customer_input])

    # One-hot encode package
    for pkg in package_options:
        input_df[pkg] = 1 if pkg == selected_package else 0

    # Ensure all columns for model
    for col in feature_columns:
        if col not in input_df.columns:
            input_df[col] = 0
    input_df = input_df[feature_columns]

    # Predict button
    if st.button("Predict Churn"):
        prob = model.predict(input_df)[0][0]
        result = "Churn" if prob > 0.5 else "No Churn"
        st.metric("Prediction", result, delta=f"{prob:.2f} Probability")