# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZHUVTKDT5ULpJSZz1yzGg6ErMZ3XvQVq
"""

# app.py

import streamlit as st
import pandas as pd
import joblib
import tensorflow as tf
from zipfile import ZipFile
import os

st.set_page_config(page_title="Customer Churn Dashboard", layout="wide")

# 1️⃣ Load ZIP file (uploaded once in Colab/Drive)
zip_path = "customer_data.zip"  # Change path if needed

if not os.path.exists("customer_data.csv"):
    with ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall()  # Extract CSV

# 2️⃣ Load dataset
@st.cache_data
def load_data():
    df = pd.read_csv("customer_data.csv")
    return df

df = load_data()

# 3️⃣ Load trained ANN model
model = tf.keras.models.load_model("ann_model.keras")

# 4️⃣ Load feature columns (saved from training)
feature_columns = joblib.load("feature_columns.pkl")

# 5️⃣ Sidebar for customer selection
st.sidebar.header("Select Customer")
customer_idx = st.sidebar.number_input(
    "Customer Index (0 - {})".format(len(df)-1),
    min_value=0,
    max_value=len(df)-1,
    value=0
)

# 6️⃣ Prediction function
def predict_customer(customer_idx):
    customer_data = df.iloc[[customer_idx]].drop(columns=["churn", "customer_id"])

    # Add missing columns if any
    for col in feature_columns:
        if col not in customer_data.columns:
            customer_data[col] = 0

    # Reorder columns to match training
    customer_data = customer_data[feature_columns]

    prediction_prob = model.predict(customer_data)[0][0]
    prediction = "Churn" if prediction_prob > 0.5 else "No Churn"
    return prediction, prediction_prob

# 7️⃣ Make prediction
prediction, prob = predict_customer(customer_idx)

# 8️⃣ Dashboard main area
st.title("Customer Churn Dashboard")
st.subheader(f"Selected Customer Index: {customer_idx}")

st.metric(label="Prediction", value=prediction, delta=f"{prob:.2f} Probability")

st.markdown("---")
st.subheader("Customer Details")
st.dataframe(df.iloc[[customer_idx]])

st.markdown("---")
st.subheader("EDA / Summary Statistics")
st.write(df.describe())

# 9️⃣ Optionally show entire dataset
if st.checkbox("Show full dataset"):
    st.dataframe(df)